/* tslint:disable */
/* eslint-disable */
/**
 * PGN Parser API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AuthStatusResponse {
    'authenticated': boolean;
    'username'?: string;
}
export interface CombinedPgnResponse {
    'combined'?: string;
}
export interface CreateLichessStudyRequest {
    'pgn'?: string;
    'studyName'?: string;
    'color'?: CreateLichessStudyRequestColorEnum;
}

export const CreateLichessStudyRequestColorEnum = {
    White: 'white',
    Black: 'black'
} as const;

export type CreateLichessStudyRequestColorEnum = typeof CreateLichessStudyRequestColorEnum[keyof typeof CreateLichessStudyRequestColorEnum];

export interface CreateLichessStudyResponse {
    'studyId'?: string;
    'url'?: string;
}
export interface PgnRequest {
    'pgn'?: string;
}
export interface SeparatedPgnResponse {
    'variations'?: Array<string>;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Current Lichess authentication state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary OAuth redirect URI; exchanges code for token and stores it in the session
         * @param {string} [code] 
         * @param {string} [state] 
         * @param {string} [error] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lichessCallback: async (code?: string, state?: string, error?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/lichess/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            if (error !== undefined) {
                localVarQueryParameter['error'] = error;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Start the Lichess OAuth (Authorization Code + PKCE) flow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lichessLogin: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/lichess/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Invalidate the Lichess session and revoke the token at Lichess
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Current Lichess authentication state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary OAuth redirect URI; exchanges code for token and stores it in the session
         * @param {string} [code] 
         * @param {string} [state] 
         * @param {string} [error] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lichessCallback(code?: string, state?: string, error?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lichessCallback(code, state, error, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.lichessCallback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Start the Lichess OAuth (Authorization Code + PKCE) flow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lichessLogin(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lichessLogin(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.lichessLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Invalidate the Lichess session and revoke the token at Lichess
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Current Lichess authentication state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<AuthStatusResponse> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary OAuth redirect URI; exchanges code for token and stores it in the session
         * @param {string} [code] 
         * @param {string} [state] 
         * @param {string} [error] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lichessCallback(code?: string, state?: string, error?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.lichessCallback(code, state, error, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Start the Lichess OAuth (Authorization Code + PKCE) flow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lichessLogin(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.lichessLogin(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Invalidate the Lichess session and revoke the token at Lichess
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Current Lichess authentication state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary OAuth redirect URI; exchanges code for token and stores it in the session
     * @param {string} [code] 
     * @param {string} [state] 
     * @param {string} [error] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lichessCallback(code?: string, state?: string, error?: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).lichessCallback(code, state, error, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Start the Lichess OAuth (Authorization Code + PKCE) flow
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lichessLogin(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).lichessLogin(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Invalidate the Lichess session and revoke the token at Lichess
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Convert a PGN into combined PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToCombined: async (pgnRequest: PgnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgnRequest' is not null or undefined
            assertParamExists('convertPgnToCombined', 'pgnRequest', pgnRequest)
            const localVarPath = `/pgn/combined`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pgnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Convert a PGN into separated PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToSeparated: async (pgnRequest: PgnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgnRequest' is not null or undefined
            assertParamExists('convertPgnToSeparated', 'pgnRequest', pgnRequest)
            const localVarPath = `/pgn/separated`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pgnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a Lichess study with the provided PGN
         * @param {CreateLichessStudyRequest} createLichessStudyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStudyAndUploadPgn: async (createLichessStudyRequest: CreateLichessStudyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createLichessStudyRequest' is not null or undefined
            assertParamExists('createStudyAndUploadPgn', 'createLichessStudyRequest', createLichessStudyRequest)
            const localVarPath = `/study`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLichessStudyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Convert a PGN into combined PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async convertPgnToCombined(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinedPgnResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.convertPgnToCombined(pgnRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.convertPgnToCombined']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Convert a PGN into separated PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async convertPgnToSeparated(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeparatedPgnResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.convertPgnToSeparated(pgnRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.convertPgnToSeparated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a Lichess study with the provided PGN
         * @param {CreateLichessStudyRequest} createLichessStudyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStudyAndUploadPgn(createLichessStudyRequest: CreateLichessStudyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateLichessStudyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createStudyAndUploadPgn(createLichessStudyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createStudyAndUploadPgn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Convert a PGN into combined PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToCombined(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombinedPgnResponse> {
            return localVarFp.convertPgnToCombined(pgnRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Convert a PGN into separated PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToSeparated(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): AxiosPromise<SeparatedPgnResponse> {
            return localVarFp.convertPgnToSeparated(pgnRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a Lichess study with the provided PGN
         * @param {CreateLichessStudyRequest} createLichessStudyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStudyAndUploadPgn(createLichessStudyRequest: CreateLichessStudyRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateLichessStudyResponse> {
            return localVarFp.createStudyAndUploadPgn(createLichessStudyRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Convert a PGN into combined PGN
     * @param {PgnRequest} pgnRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public convertPgnToCombined(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).convertPgnToCombined(pgnRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Convert a PGN into separated PGN
     * @param {PgnRequest} pgnRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public convertPgnToSeparated(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).convertPgnToSeparated(pgnRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a Lichess study with the provided PGN
     * @param {CreateLichessStudyRequest} createLichessStudyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createStudyAndUploadPgn(createLichessStudyRequest: CreateLichessStudyRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createStudyAndUploadPgn(createLichessStudyRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



