/* tslint:disable */
/* eslint-disable */
/**
 * PGN Parser API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CombinedPgnResponse {
    'combined'?: string;
}
export interface PgnRequest {
    'pgn'?: string;
}
export interface SeparatedPgnResponse {
    'variations'?: Array<string>;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Convert a PGN into combined PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToCombined: async (pgnRequest: PgnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgnRequest' is not null or undefined
            assertParamExists('convertPgnToCombined', 'pgnRequest', pgnRequest)
            const localVarPath = `/pgn/combined`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pgnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Convert a PGN into separated PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToSeparated: async (pgnRequest: PgnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgnRequest' is not null or undefined
            assertParamExists('convertPgnToSeparated', 'pgnRequest', pgnRequest)
            const localVarPath = `/pgn/separated`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pgnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Convert a PGN into combined PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async convertPgnToCombined(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinedPgnResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.convertPgnToCombined(pgnRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.convertPgnToCombined']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Convert a PGN into separated PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async convertPgnToSeparated(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SeparatedPgnResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.convertPgnToSeparated(pgnRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.convertPgnToSeparated']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Convert a PGN into combined PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToCombined(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombinedPgnResponse> {
            return localVarFp.convertPgnToCombined(pgnRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Convert a PGN into separated PGN
         * @param {PgnRequest} pgnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertPgnToSeparated(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig): AxiosPromise<SeparatedPgnResponse> {
            return localVarFp.convertPgnToSeparated(pgnRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Convert a PGN into combined PGN
     * @param {PgnRequest} pgnRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public convertPgnToCombined(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).convertPgnToCombined(pgnRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Convert a PGN into separated PGN
     * @param {PgnRequest} pgnRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public convertPgnToSeparated(pgnRequest: PgnRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).convertPgnToSeparated(pgnRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



