sonar.organization=dersiedler92
sonar.projectKey=dersiedler92_pgn-parser-frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts
sonar.test.exclusions=src/api-client/**
sonar.coverage.exclusions=src/api-client/**
sonar.exclusions=src/**/*.test.tsx,src/**/*.test.ts,src/api-client/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
