spring.application.name=pgn-parser-for-java
spring.security.user.name=alpa
spring.security.user.password=secret123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

lichess.token=lip_BbDCR9uDHtpZd9z1oEu0